truncate table specific;
truncate table modified_recipe;
truncate table favorite;
truncate table review;
truncate table substitute;
truncate table contains;
truncate table recipe CASCADE;
truncate table ingredient CASCADE;
truncate table roles;
truncate table user_diet_type  ;
truncate table users CASCADE;
truncate table general_recipe CASCADE;
truncate table diet_type CASCADE ;
