truncate table specific;
truncate table modified_recipe;
truncate table favorite;
truncate table review;
truncate table substitute;
truncate table recipe CASCADE ;
truncate table contains;
truncate table ingredient CASCADE;
truncate table general_recipe CASCADE ;
truncate table diet_type CASCADE ;
