truncate table specific;
truncate table modified_recipe;
truncate table favorite;
truncate table review;
truncate table substitute;
truncate table contains;
truncate table recipe;
truncate table ingredient CASCADE;
truncate table roles;
truncate table customer;
truncate table general_recipe;
truncate table diet_type;
