INSERT INTO generalrecipe VALUES (DEFAULT,'Bakewell tart,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Apple Frangipan Tart,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Kapsalon,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Spaghetti Bolognese,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Spicy Arrabiata Penne,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Teriyaki Chicken Casserole,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Honey Teriyaki Salmon,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Pad See Ew,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Vegan Lasagna,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Chocolate Gateau,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Mediterranean Pasta Salad,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Cream Cheese Tart,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Potato Gratin with Chicken,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Irish stew,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Lamb tomato and sweet spices,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Rigatoni with fennel sausage sauce,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Smoky Lentil Chili with Squash,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Dal fry,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Rocky Road Fudge,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Hot Chocolate Fudge,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Christmas Pudding Flapjack,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Eton Mess,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Bread and Butter Pudding,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Sticky Toffee Pudding Ultimate,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Vegan Chocolate Cake,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Chicken Handi,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Chicken Alfredo Primavera,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Spicy North African Potato Salad,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Fish pie,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Beef Wellington,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Poutine,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Lamb Biryani,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Tandoori chicken,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Baingan Bharta,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Lamb Rogan josh,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Recheado Masala Fish,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Osso Buco alla Milanese,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Ribollita,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Beef Brisket Pot Roast,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Kentucky Fried Chicken,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Thai Green Curry,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'French Lentils With Garlic and Thyme,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Roasted Eggplant With Tahini, Pine Nuts, and Lentils,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Stovetop Eggplant With Harissa, Chickpeas, and Cumin Yogurt,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Chicken Fajita Mac and Cheese,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Cajun spiced fish tacos,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Katsu Chicken curry,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Laksa King Prawn Noodles,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Toad In The Hole,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Salmon Prawn Risotto,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Beef Sunday Roast,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Braised Beef Chilli,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Massaman Beef curry,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Vietnamese Grilled Pork (bun-thit-nuong),NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Grilled Mac and Cheese Sandwich,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Crock Pot Chicken Baked Tacos,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Chicken Karaage,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Coq au vin,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Salted Caramel Cheescake,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Beef stroganoff,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Fettucine alfredo,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Pilchard puttanesca,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Venetian Duck Ragu,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Chilli prawn linguine,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Clam chowder,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Creamy Tomato Soup,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Broccoli & Stilton soup,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Lamb Tagine,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Lasagne,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Turkey Meatloaf,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Chicken & mushroom Hotpot,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Pork Cassoulet,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Bean & Sausage Hotpot,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Spinach & Ricotta Cannelloni,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Chicken Couscous,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Nutty Chicken Curry,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Tuna Nicoise,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Chocolate Avocado Mousse,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Pancakes,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Banana Pancakes,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Choc Chip Pecan Pie,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Pumpkin Pie,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'New York cheesecake,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Key Lime Pie,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Chocolate Raspberry Brownies,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Peanut Butter Cheesecake,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Peach & Blueberry Grunt,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Vegetarian Casserole,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Mushroom & Chestnut Rotolo,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Matar Paneer,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Squash linguine,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Vegetarian Chilli,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Kidney Bean Curry,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Tahini Lentils,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Chickpea Fajitas,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Yaki Udon,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Spanish Tortilla,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Beef Dumpling Stew,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Beef and Mustard Pie,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Chicken Ham and Leek Pie,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Minced Beef Pie,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Lamb and Potato pie,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Beef and Oyster pie,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Chicken Parmentier,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'McSinghs Scotch pie,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Steak and Kidney Pie,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Three Fish Pie,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Sticky Toffee Pudding,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Lancashire hotpot,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,' Bubble & Squeak,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Spotted Dick,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Kedgeree,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Eccles Cakes,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Summer Pudding,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Jam Roly-Poly,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Blackberry Fool,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Treacle Tart,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Apple & Blackberry Crumble,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Battenberg Cake,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'English Breakfast,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Full English Breakfast,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Carrot Cake,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Chelsea Buns,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Dundee cake,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Madeira Cake,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Rock Cakes,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Parkin Cake,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'French Onion Soup,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Beef Bourguignon,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Chocolate Souffle,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Flamiche,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Duck Confit,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Ratatouille,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Tarte Tatin,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Chinon Apple Tarts,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Summer Pistou,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Three-cheese souffles,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Brie wrapped in prosciutto & brioche,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'French Omelette,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Pear Tarte Tatin,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'White chocolate creme brulee,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Fish Stew with Rouille,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Fennel Dauphinoise,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Chicken Marengo,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Provençal Omelette Cake,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Prawn & Fennel Bisque,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Canadian Butter Tarts,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Nanaimo Bars,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Split Pea Soup,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Tourtiere,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Montreal Smoked Meat,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'BeaverTails,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Timbits,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Pate Chinois,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Sugar Pie,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Pouding chomeur,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Rappie Pie,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Chicken Basquaise,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Steak Diane,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Saltfish and Ackee,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Jerk chicken with rice & peas,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Jamaican Beef Patties,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Callaloo Jamaican Style,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Brown Stew Chicken,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Red Peas Soup,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Roast fennel and aubergine paella,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Oxtail with broad beans,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Escovitch Fish,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Kung Pao Chicken,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Kung Po Prawns,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Ma Po Tofu,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Wontons,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Sweet and Sour Pork,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Szechuan Beef,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'General Tsos Chicken,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Beef Lo Mein,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Shrimp Chow Fun,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Hot and Sour Soup,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Egg Drop Soup,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Chicken Congee,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Fruit and Cream Cheese Breakfast Pastries,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Peanut Butter Cookies,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Baked salmon with fennel & tomatoes,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Salmon Avocado Salad,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Budino Di Ricotta,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Salmon Eggs Eggs Benedict,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Shakshuka,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Smoked Haddock Kedgeree,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Breakfast Potatoes,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Chocolate Caramel Crispy,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Home-made Mandazi,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Mbuzi Choma (Roasted Goat),NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Chakchouka ,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Tunisian Orange Cake,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Kafteji,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Tunisian Lamb Soup,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Leblebi Soup,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Keleya Zaara,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Tuna and Egg Briks,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Cashew Ghoriba Biscuits,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Corba,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Kumpir,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Bitterballen (Dutch meatballs),NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Stamppot,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Snert (Dutch Split Pea Soup),NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Spaghetti alla Carbonara,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Lasagna Sandwiches,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Classic Christmas pudding,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Christmas Pudding Trifle,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Christmas cake,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Mince Pies,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Soy-Glazed Meatloaves with Wasabi Mashed Potatoes & Roasted Carrots,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Honey Balsamic Chicken with Crispy Broccoli & Potatoes,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Skillet Apple Pork Chops with Roasted Sweet Potatoes & Zucchini,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'BBQ Pork Sloppy Joes,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'French Onion Chicken with Roasted Carrots & Mashed Potatoes,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Beef Banh Mi Bowls with Sriracha Mayo, Carrot & Pickled Cucumber,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Corned Beef and Cabbage,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Crispy Sausages and Greens,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Vegetable Shepherds Pie,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Strawberry Rhubarb Pie,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Moussaka,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Honey Yogurt Cheesecake,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Stuffed Lamb Tomatoes,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Lamb and Lemon Souvlaki,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Lamb Tzatziki Burgers,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Chicken Quinoa Greek Salad,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Gigantes Plaki,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Big Mac,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Pizza Express Margherita,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Krispy Kreme Donut,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Chick-Fil-A Sandwich,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Paszteciki (Polish Pasties),NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Bigos (Hunters Stew),NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Pierogi (Polish Dumplings),NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Rosó³ (Polish Chicken Soup),NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Go³¹bki (cabbage roll),NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Polskie Naleœniki (Polish Pancakes),NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Sledz w Oleju (Polish Herrings),NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Rogaliki (Polish Croissant Cookies),NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Ful Medames,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Tamiya,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Koshari,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Shawarma,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Mulukhiyah,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Feteer Meshaltet,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Egyptian Fatteh,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Tonkatsu pork,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Japanese gohan rice,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Japanese Katsudon,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Ham hock colcannon,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Boxty Breakfast,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Coddled pork with cider,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Mustard champ,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Piri-piri chicken and slaw,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Spring onion and prawn empanadas,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Grilled Portuguese sardines,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Portuguese prego with green piri-piri,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Fish fofos,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Portuguese barbecued pork (Febras assadas),NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Portuguese fish stew (Caldeirada de peixe),NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Portuguese custard tarts,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Moroccan Carrot Soup,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Mee goreng mamak,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Apam balik,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Ayam Percik,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Nasi lemak,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Roti john,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Beef Rendang,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Seri muka kuih,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Cevapi Sausages,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Croatian lamb peka,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Traditional Croatian Goulash,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Croatian Bean Stew,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Mushroom soup with buckwheat,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Burek,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Fresh sardines,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Walnut Roll Gužvara,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Chivito uruguayo,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Fettuccine Alfredo,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Sushi,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Stuffed Bell Peppers with Quinoa and Black Beans,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Beef Mechado,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Bistek,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Beef Caldereta,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Beef Asado,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Crispy Eggplant,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Eggplant Adobo,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Grilled eggplant with coconut milk,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Tortang Talong,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Bread omelette,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Cabbage Soup (Shchi),NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Beetroot Soup (Borscht),NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Fish Soup (Ukha),NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Blini Pancakes,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Potato Salad (Olivier Salad),NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Strawberries Romanoff,NULL,NULL,NULL');
INSERT INTO generalrecipe VALUES (DEFAULT,'Lamb Pilaf (Plov),NULL,NULL,NULL');
